import type { Metadata } from "next";
import "./globals.css";
import MainNavBar from "./components/Navigation/MainNavBar";
import SignUpModal from "./components/modals/SignUpModal";
import LoginModal from "./components/modals/LogInModal";
import AddPropertyModal from "./components/modals/AddPropertyModal";
import SuccessModal from "./components/modals/SuccesModal";
import SearchModal from "./components/modals/SearchModal";
import DeleteModal from "./components/modals/DeleteModal"
import Footer from "./components/footer/Footer"



export const metadata: Metadata = {
  title: "Demo Booking.com",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen"> {/* Ensure the body has full height */}
        <MainNavBar />
        <main className="flex-grow"> {/* Use flex-grow to allow the main content to take available space */}
          {children}
        </main>
        <Footer /> {/* Include the Footer here */}
        <SignUpModal />
        <LoginModal />
        <AddPropertyModal />
        <SuccessModal />
        <SearchModal />
        <DeleteModal />
      </body>
    </html>
  );
}
