# Generated by Django 5.1.1 on 2024-09-29 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0002_rename_is_active_user_is_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_verified',
            new_name='is_active',
        ),
    ]
