# Generated by Django 5.1.1 on 2024-09-30 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0003_rename_is_verified_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='/uploads/avatar/default-avatar.png', upload_to='uploads/avatar'),
        ),
    ]
