# Generated by Django 5.1.1 on 2024-10-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='guests',
            field=models.IntegerField(),
        ),
    ]
